import React from "react";
import Head from "next/head";
import Nav from "./Nav";

export default function Layout(props) {
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta charset="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/next.svg" />
        {/* <link rel="icon" href={props.logo} /> */}
      </Head>
      <Nav />
      <div>{props.children}</div>
    </div>
  );
}
