import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Projects from "../components/Projects";
import Nav from "../components/Nav";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <>
      <Layout title="My Portfolio" logo="/next.svg">
        <Content />
        <Skills />
        <Projects />
        <Contact />
        <Footer />
       
      </Layout>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>
      <body className="container mx-auto">
        <div>
          <Nav />
          <div className="mt-24">
            <Content />
          </div>
          <Skills />
          <Projects />
          <Contact />
          <Footer />
        </div>
      </body> */}
    </>
  );
}
