import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Projects from "../components/Projects";
import Nav from "../components/Nav";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <>
      <Layout title="My Portfolio" logo="/next.svg">
        {/* <Content /> */}
        <div class="lg:flex">
          <div class="flex items-center justify-center w-full px-6 py-8 lg:h-[32rem] lg:w-1/2">
            <div class="max-w-xl">
              <h2 class="text-3xl font-semibold text-gray-800  lg:text-4xl">
                Build Your New <span class="text-blue-600 ">Idea</span>
              </h2>

              <p class="mt-4 text-sm text-gray-500  lg:text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis commodi cum cupiditate ducimus, fugit harum id necessitatibus odio quam quasi, quibusdam rem tempora voluptates.
              </p>

              <div class="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <a href="#" class="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-gray-900 rounded-md hover:bg-gray-700">
                  Get Started
                </a>
                <a href="#" class="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-gray-700 uppercase transition-colors duration-300 transform bg-gray-200 rounded-md lg:mx-4 hover:bg-gray-300">
                  Learn More
                </a>
              </div>
            </div>
          </div>

          <div class="w-full h-64 lg:w-1/2 lg:h-auto">
            <div class="w-full h-full bg-top overflow-hidden" style={{ backgroundImage: "url(/my.png)" }}>
              {/* <div class="w-full h-full bg-black opacity-25"></div> */}
            </div>
          </div>
        </div>
        <Skills />
        <Projects />
        <Contact />
        <Footer />
      </Layout>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>
      <body className="container mx-auto">
        <div>
          <Nav />
          <div className="mt-24">
            <Content />
          </div>
          <Skills />
          <Projects />
          <Contact />
          <Footer />
        </div>
      </body> */}
    </>
  );
}
