import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Projects from "../components/Projects";
import Nav from "../components/Nav";
import Skills from "../components/Skills";
import Contact from "../components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="container mx-auto">
        <div>
          <Nav />
          <div className="mt-24">
            <Content />
          </div>
          <Skills />
          <Projects />
          <Contact />
          <Footer />
        </div>
      </body>
    </>
  );
}
